### ISSUE TITLE
编译项目报错

### ISSUE THREAD

**Issue by TheWalkingDead1024** [o2team/taro-ebook-source#11]
编译taro-demo为微信小程序的时候有报错如下
开始编译项目 toplife-weapp
path.js:1259
  dirname: function dirname(path) {
                           ^

RangeError: Maximum call stack size exceeded
    at Object.dirname (path.js:1259:28)
    at Object.exports.recursiveFindNodeModules (/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:540:24)
    at Object.exports.recursiveFindNodeModules (/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:545:18)
    at Object.exports.recursiveFindNodeModules (/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:545:18)
    at Object.exports.recursiveFindNodeModules (/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:545:18)
    at Object.exports.recursiveFindNodeModules (/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:545:18)
    at Object.exports.recursiveFindNodeModules (/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:545:18)
    at Object.exports.recursiveFindNodeModules (/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:545:18)
    at Object.exports.recursiveFindNodeModules (/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:545:18)
    at Object.exports.recursiveFindNodeModules (/usr/local/lib/node_modules/@tarojs/cli/src/util/index.js:545:18)

**Comment by TheWalkingDead1024** [comment]
在taro-demo/client进行编译，编译命令为taro build --type weapp --watc

**Comment by Bless-L** [comment]
taro版本是多少？cli及项目相关依赖更新到最新版本试试
