### ISSUE TITLE
请问这个项目怎么可以运行起来？报了好多错。。

### ISSUE THREAD

**Issue by alvinli1008** [o2team/taro-ebook-source#14]
![shop](https://user-images.githubusercontent.com/47051702/58758102-0c7aec00-8549-11e9-93b8-8db1850a581b.PNG)

**Comment by leechaouser** [comment]
VM6342:1 获取 wx.getUserInfo 接口后续将不再出现授权弹窗，请注意升级
参考文档: https://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=1650183953&docid=0000a26e1aca6012e896a517556c01
console.warn @ VM6342:1
operateWXData @ appservice?t=1560782505275:2585
invoke @ appservice?t=1560782505275:2585
invoke @ WAService.js:1
i @ WAService.js:1
(anonymous) @ WAService.js:1
getUserInfo @ WAService.js:1
m @ WAService.js:1
TC.(anonymous function) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ index.js:4283
taro.(anonymous function) @ index.js:4259
_callee$ @ wx.js:28
tryCatch @ runtime.js:62
invoke @ runtime.js:281
prototype.(anonymous function) @ runtime.js:110
step @ wx.js:147
(anonymous) @ wx.js:147
(anonymous) @ wx.js:147
getWxUserData @ wx.js:51
_callee$ @ app.js:101
tryCatch @ runtime.js:62
invoke @ runtime.js:281
prototype.(anonymous function) @ runtime.js:110
step @ app.js:27
(anonymous) @ app.js:27
(anonymous) @ app.js:27
componentWillMount @ app.js:117
onLaunch @ index.js:4076
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
he @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ app.js:132
require @ WAService.js:1
(anonymous) @ VM6506:1
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 [Taro warn] 请给组件提供一个 `defaultProps` 以提高初次渲染性能！
console.warn @ VM6342:1
createComponent @ index.js:3571
(anonymous) @ edit_box.js:156
require @ WAService.js:1
(anonymous) @ VM6506:113
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 TypeError: Cannot read property 'value' of undefined
    at Connect._createData (edit_box.js:114)
    at Object.createComponent (index.js:3566)
    at edit_box.js:156
    at require (WAService.js:1)
    at <anonymous>:113:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1560782505275:2834)
    at HTMLScriptElement.script.onload (appservice?t=1560782505275:2846)
console.warn @ VM6342:1
createComponent @ index.js:3574
(anonymous) @ edit_box.js:156
require @ WAService.js:1
(anonymous) @ VM6506:113
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 [Taro warn] 请给组件提供一个 `defaultProps` 以提高初次渲染性能！
console.warn @ VM6342:1
createComponent @ index.js:3571
(anonymous) @ bottom_bar.js:252
require @ WAService.js:1
(anonymous) @ VM6506:161
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (bottom_bar.js:188)
    at Object.createComponent (index.js:3566)
    at bottom_bar.js:252
    at require (WAService.js:1)
    at <anonymous>:161:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1560782505275:2834)
    at HTMLScriptElement.script.onload (appservice?t=1560782505275:2846)
console.warn @ VM6342:1
createComponent @ index.js:3574
(anonymous) @ bottom_bar.js:252
require @ WAService.js:1
(anonymous) @ VM6506:161
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 [Taro warn] 请给组件提供一个 `defaultProps` 以提高初次渲染性能！
console.warn @ VM6342:1
createComponent @ index.js:3571
(anonymous) @ commodity_container.js:157
require @ WAService.js:1
(anonymous) @ VM6506:167
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (commodity_container.js:81)
    at Object.createComponent (index.js:3566)
    at commodity_container.js:157
    at require (WAService.js:1)
    at <anonymous>:167:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1560782505275:2834)
    at HTMLScriptElement.script.onload (appservice?t=1560782505275:2846)
console.warn @ VM6342:1
createComponent @ index.js:3574
(anonymous) @ commodity_container.js:157
require @ WAService.js:1
(anonymous) @ VM6506:167
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 [Taro warn] 请给页面提供初始 `state` 以提高初次渲染性能！
console.warn @ VM6342:1
createComponent @ index.js:3569
(anonymous) @ shop.js:266
require @ WAService.js:1
(anonymous) @ VM6506:173
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (shop.js:204)
    at Object.createComponent (index.js:3566)
    at shop.js:266
    at require (WAService.js:1)
    at <anonymous>:173:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1560782505275:2834)
    at HTMLScriptElement.script.onload (appservice?t=1560782505275:2846)
console.warn @ VM6342:1
createComponent @ index.js:3574
(anonymous) @ shop.js:266
require @ WAService.js:1
(anonymous) @ VM6506:173
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 [Taro warn] 请给页面提供初始 `state` 以提高初次渲染性能！
console.warn @ VM6342:1
createComponent @ index.js:3569
(anonymous) @ list.js:216
require @ WAService.js:1
(anonymous) @ VM6506:179
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (list.js:192)
    at Object.createComponent (index.js:3566)
    at list.js:216
    at require (WAService.js:1)
    at <anonymous>:179:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1560782505275:2834)
    at HTMLScriptElement.script.onload (appservice?t=1560782505275:2846)
console.warn @ VM6342:1
createComponent @ index.js:3574
(anonymous) @ list.js:216
require @ WAService.js:1
(anonymous) @ VM6506:179
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 [Taro warn] 请给组件提供一个 `defaultProps` 以提高初次渲染性能！
console.warn @ VM6342:1
createComponent @ index.js:3571
(anonymous) @ commodity.js:318
require @ WAService.js:1
(anonymous) @ VM6506:191
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 TypeError: (0 , _index.genCompid) is not a function
    at Commondity._createData (commodity.js:292)
    at Object.createComponent (index.js:3566)
    at commodity.js:318
    at require (WAService.js:1)
    at <anonymous>:191:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1560782505275:2834)
    at HTMLScriptElement.script.onload (appservice?t=1560782505275:2846)
console.warn @ VM6342:1
createComponent @ index.js:3574
(anonymous) @ commodity.js:318
require @ WAService.js:1
(anonymous) @ VM6506:191
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 [Taro warn] 请给页面提供初始 `state` 以提高初次渲染性能！
console.warn @ VM6342:1
createComponent @ index.js:3569
(anonymous) @ cart_sub.js:181
require @ WAService.js:1
(anonymous) @ VM6506:197
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (cart_sub.js:131)
    at Object.createComponent (index.js:3566)
    at cart_sub.js:181
    at require (WAService.js:1)
    at <anonymous>:197:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1560782505275:2834)
    at HTMLScriptElement.script.onload (appservice?t=1560782505275:2846)
console.warn @ VM6342:1
createComponent @ index.js:3574
(anonymous) @ cart_sub.js:181
require @ WAService.js:1
(anonymous) @ VM6506:197
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 [Taro warn] 请给页面提供初始 `state` 以提高初次渲染性能！
console.warn @ VM6342:1
createComponent @ index.js:3569
(anonymous) @ index.js:300
require @ WAService.js:1
(anonymous) @ VM6506:203
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (index.js:256)
    at Object.createComponent (index.js:3566)
    at index.js:300
    at require (WAService.js:1)
    at <anonymous>:203:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1560782505275:2834)
    at HTMLScriptElement.script.onload (appservice?t=1560782505275:2846)
console.warn @ VM6342:1
createComponent @ index.js:3574
(anonymous) @ index.js:300
require @ WAService.js:1
(anonymous) @ VM6506:203
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 [Taro warn] 请给页面提供初始 `state` 以提高初次渲染性能！
console.warn @ VM6342:1
createComponent @ index.js:3569
(anonymous) @ detail.js:406
require @ WAService.js:1
(anonymous) @ VM6506:209
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (detail.js:342)
    at Object.createComponent (index.js:3566)
    at detail.js:406
    at require (WAService.js:1)
    at <anonymous>:209:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1560782505275:2834)
    at HTMLScriptElement.script.onload (appservice?t=1560782505275:2846)
console.warn @ VM6342:1
createComponent @ index.js:3574
(anonymous) @ detail.js:406
require @ WAService.js:1
(anonymous) @ VM6506:209
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 [Taro warn] 请给页面提供初始 `state` 以提高初次渲染性能！
console.warn @ VM6342:1
createComponent @ index.js:3569
(anonymous) @ balance.js:273
require @ WAService.js:1
(anonymous) @ VM6506:215
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (balance.js:214)
    at Object.createComponent (index.js:3566)
    at balance.js:273
    at require (WAService.js:1)
    at <anonymous>:215:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1560782505275:2834)
    at HTMLScriptElement.script.onload (appservice?t=1560782505275:2846)
console.warn @ VM6342:1
createComponent @ index.js:3574
(anonymous) @ balance.js:273
require @ WAService.js:1
(anonymous) @ VM6506:215
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 [Taro warn] 请给组件提供一个 `defaultProps` 以提高初次渲染性能！
console.warn @ VM6342:1
createComponent @ index.js:3571
(anonymous) @ searchFilter.js:183
require @ WAService.js:1
(anonymous) @ VM6506:221
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 TypeError: (0 , _index.genCompid) is not a function
    at SearchFilter._createData (searchFilter.js:162)
    at Object.createComponent (index.js:3566)
    at searchFilter.js:183
    at require (WAService.js:1)
    at <anonymous>:221:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1560782505275:2834)
    at HTMLScriptElement.script.onload (appservice?t=1560782505275:2846)
console.warn @ VM6342:1
createComponent @ index.js:3574
(anonymous) @ searchFilter.js:183
require @ WAService.js:1
(anonymous) @ VM6506:221
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 [Taro warn] 请给页面提供初始 `state` 以提高初次渲染性能！
console.warn @ VM6342:1
createComponent @ index.js:3569
(anonymous) @ cart.js:175
require @ WAService.js:1
(anonymous) @ VM6506:227
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (cart.js:131)
    at Object.createComponent (index.js:3566)
    at cart.js:175
    at require (WAService.js:1)
    at <anonymous>:227:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1560782505275:2834)
    at HTMLScriptElement.script.onload (appservice?t=1560782505275:2846)
console.warn @ VM6342:1
createComponent @ index.js:3574
(anonymous) @ cart.js:175
require @ WAService.js:1
(anonymous) @ VM6506:227
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 [Taro warn] 请给页面提供初始 `state` 以提高初次渲染性能！
console.warn @ VM6342:1
createComponent @ index.js:3569
(anonymous) @ list.js:261
require @ WAService.js:1
(anonymous) @ VM6506:233
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
VM6342:1 TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (list.js:171)
    at Object.createComponent (index.js:3566)
    at list.js:261
    at require (WAService.js:1)
    at <anonymous>:233:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1560782505275:2834)
    at HTMLScriptElement.script.onload (appservice?t=1560782505275:2846)
console.warn @ VM6342:1
createComponent @ index.js:3574
(anonymous) @ list.js:261
require @ WAService.js:1
(anonymous) @ VM6506:233
scriptLoaded @ appservice?t=1560782505275:2834
script.onload @ appservice?t=1560782505275:2846
redux-logger.js:163  action REQUEST_HOME @ 22:41:48.600
redux-logger.js:170  prev state {detail: {…}, home: {…}, shop: {…}, search: {…}, orderDetail: {…}, …}
redux-logger.js:172  action     {type: "REQUEST_HOME", payload: null}
redux-logger.js:174  error      TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (index.js:256)
    at doUpdate (index.js:3770)
    at updateComponent (index.js:3754)
    at Connect.forceUpdate (index.js:3977)
    at Connect.stateListener (index.js:251)
    at dispatch (redux.js:219)
    at redux-logger.js:207
    at index.js:14
    at dispatch (redux.js:610)
    at _callee$ (home.js:76)
redux-logger.js:176  next state {detail: {…}, home: {…}, shop: {…}, search: {…}, orderDetail: {…}, …}
VM6342:1 thirdScriptError
(0 , _index.genCompid) is not a function;at "pages/index/index" page lifeCycleMethod onLoad function
TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (http://127.0.0.1:11044/appservice/pages/index/index.js:256:45)
    at doUpdate (http://127.0.0.1:11044/appservice/npm/@tarojs/taro-weapp/dist/index.js:3770:22)
    at updateComponent (http://127.0.0.1:11044/appservice/npm/@tarojs/taro-weapp/dist/index.js:3754:5)
    at Y.initComponent (http://127.0.0.1:11044/appservice/npm/@tarojs/taro-weapp/dist/index.js:3554:3)
    at Y.weappComponentConf.methods.onLoad (http://127.0.0.1:11044/appservice/npm/@tarojs/taro-weapp/dist/index.js:3646:21)
    at Y.<anonymous> (http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:1078909)
    at Y.p.__callPageLifeTime__ (http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:1078668)
    at kt (http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:1092319)
    at http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:1095061
    at It (http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:1095124)
console.error @ VM6342:1
errorReport @ WAService.js:1
thirdErrorReport @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
p.__callPageLifeTime__ @ WAService.js:1
kt @ WAService.js:1
(anonymous) @ WAService.js:1
It @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
i.emit @ WAService.js:1
emit @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1560782505275:2585
n.registerCallback.t @ appservice?t=1560782505275:2585
u.forEach.t @ appservice?t=1560782505275:2585
(anonymous) @ appservice?t=1560782505275:2585
a.onmessage @ appservice?t=1560782505275:2585
home.js:54 Uncaught (in promise) TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (index.js:256)
    at doUpdate (index.js:3770)
    at updateComponent (index.js:3754)
    at Connect.forceUpdate (index.js:3977)
    at Connect.stateListener (index.js:251)
    at dispatch (redux.js:219)
    at redux-logger.js:207
    at index.js:14
    at dispatch (redux.js:610)
    at _callee$ (home.js:76)
_createData @ index.js:256
doUpdate @ index.js:3770
updateComponent @ index.js:3754
forceUpdate @ index.js:3977
stateListener @ index.js:251
dispatch @ redux.js:219
(anonymous) @ redux-logger.js:207
(anonymous) @ index.js:14
dispatch @ redux.js:610
_callee$ @ home.js:76
tryCatch @ runtime.js:62
invoke @ runtime.js:281
prototype.(anonymous function) @ runtime.js:110
step @ home.js:54
(anonymous) @ home.js:54
(anonymous) @ home.js:54
(anonymous) @ home.js:130
(anonymous) @ index.js:11
onFetchIndexList @ index.js:294
componentWillMount @ index.js:168
componentWillMount @ index.js:289
componentTrigger @ index.js:3512
updateComponent @ index.js:3750
initComponent @ index.js:3554
weappComponentConf.methods.onLoad @ index.js:3646
(anonymous) @ WAService.js:1
p.__callPageLifeTime__ @ WAService.js:1
kt @ WAService.js:1
(anonymous) @ WAService.js:1
It @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
i.emit @ WAService.js:1
emit @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1560782505275:2585
n.registerCallback.t @ appservice?t=1560782505275:2585
u.forEach.t @ appservice?t=1560782505275:2585
(anonymous) @ appservice?t=1560782505275:2585
a.onmessage @ appservice?t=1560782505275:2585
appservice?t=1560782505275:2585 Mon Jun 17 2019 22:41:48 GMT+0800 (中国标准时间) 接口调整
VM6342:1 获取 wx.getUserInfo 接口后续将不再出现授权弹窗，请注意升级
参考文档: https://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=1650183953&docid=0000a26e1aca6012e896a517556c01
console.warn @ VM6342:1
operateWXData @ appservice?t=1560782505275:2585
invoke @ appservice?t=1560782505275:2585
invoke @ WAService.js:1
i @ WAService.js:1
(anonymous) @ WAService.js:1
getUserInfo @ WAService.js:1
m @ WAService.js:1
TC.(anonymous function) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ index.js:4283
taro.(anonymous function) @ index.js:4259
_callee$ @ index.js:28
tryCatch @ runtime.js:62
invoke @ runtime.js:281
prototype.(anonymous function) @ runtime.js:110
step @ index.js:177
(anonymous) @ index.js:177
(anonymous) @ index.js:177
getUserInfo @ index.js:51
_callee3$ @ index.js:121
tryCatch @ runtime.js:62
invoke @ runtime.js:281
prototype.(anonymous function) @ runtime.js:110
step @ index.js:177
(anonymous) @ index.js:177
Promise resolved (async)
step @ index.js:177
(anonymous) @ index.js:177
(anonymous) @ index.js:177
getIsAuth @ index.js:165
componentDidMount @ index.js:225
componentTrigger @ index.js:3512
weappComponentConf.methods.onReady @ index.js:3651
(anonymous) @ WAService.js:1
p.__callPageLifeTime__ @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1560782505275:2585
r.registerCallback.t @ appservice?t=1560782505275:2585
u.forEach.t @ appservice?t=1560782505275:2585
(anonymous) @ appservice?t=1560782505275:2585
a.onmessage @ appservice?t=1560782505275:2585
wx.js:38 {errMsg: "getUserInfo:fail scope unauthorized"}
wx.js:39 微信登录或用户接口故障
index.js:38 {errMsg: "getUserInfo:fail scope unauthorized"}
index.js:39 微信登录或用户接口故障
appservice?t=1560782505275:2585 Mon Jun 17 2019 22:41:49 GMT+0800 (中国标准时间) 接口调整
VM6342:1 获取 wx.getUserInfo 接口后续将不再出现授权弹窗，请注意升级
参考文档: https://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=1650183953&docid=0000a26e1aca6012e896a517556c01
console.warn @ VM6342:1
operateWXData @ appservice?t=1560782505275:2585
invoke @ appservice?t=1560782505275:2585
invoke @ WAService.js:1
i @ WAService.js:1
(anonymous) @ WAService.js:1
getUserInfo @ WAService.js:1
m @ WAService.js:1
TC.(anonymous function) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ index.js:4283
taro.(anonymous function) @ index.js:4259
_callee$ @ index.js:28
tryCatch @ runtime.js:62
invoke @ runtime.js:281
prototype.(anonymous function) @ runtime.js:110
step @ index.js:177
(anonymous) @ index.js:177
(anonymous) @ index.js:177
getUserInfo @ index.js:51
_callee2$ @ index.js:184
tryCatch @ runtime.js:62
invoke @ runtime.js:281
prototype.(anonymous function) @ runtime.js:110
step @ index.js:33
(anonymous) @ index.js:33
(anonymous) @ index.js:33
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
setTimeout (async)
setTimeout @ WAService.js:1
componentDidMount @ index.js:177
componentTrigger @ index.js:3512
weappComponentConf.methods.onReady @ index.js:3651
(anonymous) @ WAService.js:1
p.__callPageLifeTime__ @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1560782505275:2585
r.registerCallback.t @ appservice?t=1560782505275:2585
u.forEach.t @ appservice?t=1560782505275:2585
(anonymous) @ appservice?t=1560782505275:2585
a.onmessage @ appservice?t=1560782505275:2585
index.js:38 {errMsg: "getUserInfo:fail scope unauthorized"}
index.js:39 微信登录或用户接口故障
index.js:4273 Uncaught (in promise) {errMsg: "getStorage:fail data not found"}
obj.(anonymous function) @ index.js:4273
function.o.(anonymous function) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
v @ WAService.js:1
(anonymous) @ WAService.js:1
function.setTimeout @ appservice?t=1560782505275:2585
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
setTimeout (async)
setTimeout @ WAService.js:1
v @ appservice?t=1560782505275:2585
r.registerCallback.t @ appservice?t=1560782505275:2585
u.forEach.t @ appservice?t=1560782505275:2585
(anonymous) @ appservice?t=1560782505275:2585
a.onmessage @ appservice?t=1560782505275:2585
VM6342:1 thirdScriptError
(0 , _index.genCompid) is not a function;at api nextTick callback function
TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (http://127.0.0.1:11044/appservice/pages/index/index.js:256:45)
    at doUpdate (http://127.0.0.1:11044/appservice/npm/@tarojs/taro-weapp/dist/index.js:3770:22)
    at updateComponent (http://127.0.0.1:11044/appservice/npm/@tarojs/taro-weapp/dist/index.js:3754:5)
    at rerender (http://127.0.0.1:11044/appservice/npm/@tarojs/taro-weapp/dist/index.js:3860:7)
    at http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:101748
    at Function.sf (http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:583136)
    at http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:101748
    at http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:89930

**Comment by alvinli1008** [comment]
VM6666:1 thirdScriptError
(0 , _index.genCompid) is not a function;at api nextTick callback function
TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (http://127.0.0.1:11044/appservice/pages/index/index.js:256:45)
    at doUpdate (http://127.0.0.1:11044/appservice/npm/@tarojs/taro-weapp/dist/index.js:3770:22)
    at updateComponent (http://127.0.0.1:11044/appservice/npm/@tarojs/taro-weapp/dist/index.js:3754:5)
    at rerender (http://127.0.0.1:11044/appservice/npm/@tarojs/taro-weapp/dist/index.js:3860:7)
    at http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:101748
    at Function.sf (http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:583136)
    at http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:101748
    at http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:89930

VM6666:1 thirdScriptError
(0 , _index.genCompid) is not a function;at "pages/index/index" page lifeCycleMethod onLoad function
TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (http://127.0.0.1:11044/appservice/pages/index/index.js:256:45)
    at doUpdate (http://127.0.0.1:11044/appservice/npm/@tarojs/taro-weapp/dist/index.js:3770:22)
    at updateComponent (http://127.0.0.1:11044/appservice/npm/@tarojs/taro-weapp/dist/index.js:3754:5)
    at Y.initComponent (http://127.0.0.1:11044/appservice/npm/@tarojs/taro-weapp/dist/index.js:3554:3)
    at Y.weappComponentConf.methods.onLoad (http://127.0.0.1:11044/appservice/npm/@tarojs/taro-weapp/dist/index.js:3646:21)
    at Y.<anonymous> (http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:1078909)
    at Y.p.__callPageLifeTime__ (http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:1078668)
    at kt (http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:1092319)
    at http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:1095061
    at It (http://127.0.0.1:11044/appservice/__dev__/WAService.js:1:1095124)
console.error @ VM6666:1
errorReport @ WAService.js:1
thirdErrorReport @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
p.__callPageLifeTime__ @ WAService.js:1
kt @ WAService.js:1
(anonymous) @ WAService.js:1
It @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
i.emit @ WAService.js:1
emit @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1560782653164:2585
n.registerCallback.t @ appservice?t=1560782653164:2585
u.forEach.t @ appservice?t=1560782653164:2585
(anonymous) @ appservice?t=1560782653164:2585
a.onmessage @ appservice?t=1560782653164:2585
home.js:54 Uncaught (in promise) TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (index.js:256)
    at doUpdate (index.js:3770)
    at updateComponent (index.js:3754)
    at Connect.forceUpdate (index.js:3977)
    at Connect.stateListener (index.js:251)
    at dispatch (redux.js:219)
    at redux-logger.js:207
    at index.js:14
    at dispatch (redux.js:610)
    at _callee$ (home.js:76)


TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (list.js:171)
    at Object.createComponent (index.js:3566)
    at list.js:261
    at require (WAService.js:1)
    at <anonymous>:233:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1560782653164:2834)
    at HTMLScriptElement.script.onload (appservice?t=1560782653164:2846)
console.warn @ VM6666:1
createComponent @ index.js:3574
(anonymous) @ list.js:261
require @ WAService.js:1
(anonymous) @ VM6821:233
scriptLoaded @ appservice?t=1560782653164:2834
script.onload @ appservice?t=1560782653164:2846
redux-logger.js:163  action REQUEST_HOME @ 22:44:15.091
redux-logger.js:170  prev state {detail: {…}, home: {…}, shop: {…}, search: {…}, orderDetail: {…}, …}
redux-logger.js:172  action     {type: "REQUEST_HOME", payload: null}
redux-logger.js:174  error      TypeError: (0 , _index.genCompid) is not a function
    at Connect._createData (index.js:256)
    at doUpdate (index.js:3770)
    at updateComponent (index.js:3754)
    at Connect.forceUpdate (index.js:3977)
    at Connect.stateListener (index.js:251)
    at dispatch (redux.js:219)
    at redux-logger.js:207
    at index.js:14
    at dispatch (redux.js:610)
    at _callee$ (home.js:76)
redux-logger.js:176  next state {detail: {…}, home: {…}, shop: {…}, search: {…}, orderDetail: {…}, …}

**Comment by sunsmeil** [comment]
把云函数弄好就会跑起来，但是里面购物车订单都是不全的

**Comment by sunsmeil** [comment]
我跑起来了 有些云函数更新数据的函数是老的 要自己调一下

**Comment by blackjack0v0** [comment]
关键在于package.json里面很多依赖跟你的taro版本不符合，可以将里面的包更新为与你taro版本符合的就可以运行了。不过还有一些其他的报错....
