### ISSUE TITLE
taro-demo项目微信能跑起来，但是首页购物车2个tab页一直加载不出内容

### ISSUE THREAD

**Issue by lvjl** [o2team/taro-ebook-source#8]
Uncaught (in promise) TypeError: Cannot read property 'result' of undefined
    at _callee$ (http://127.0.0.1:46528/appservice/actions/cart.js:126:25)
    at tryCatch (http://127.0.0.1:46528/appservice/npm/@tarojs/async-await/npm/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (http://127.0.0.1:46528/appservice/npm/@tarojs/async-await/npm/regenerator-runtime/runtime.js:281:22)
    at Generator.prototype.(anonymous function) [as next] (http://127.0.0.1:46528/appservice/npm/@tarojs/async-await/npm/regenerator-runtime/runtime.js:110:21)
    at step (http://127.0.0.1:46528/appservice/actions/cart.js:36:191)
    at http://127.0.0.1:46528/appservice/actions/cart.js:36:361
    at <anonymous>

**Comment by Bless-L** [comment]
应该是云函数没拉到数据吧，你看看云函数日志

**Comment by lvjl** [comment]
我看了下云函数日志，是没有记录，云开发的数据库我把数据上传了，云函数也部署上传了，为什么云函数会没拉到数据，还是还需要其他操作

**Comment by lvjl** [comment]
好像所有的云函数都有这个问题，请问下这个报错是什么原因，我云函数重新构建部署了一遍还是这样，从云函数从图标变成云的logo和提示来看我云函数构建应该没问题
Error: errCode: -404011 cloud function execution error | errMsg: cloud.callFunction:fail requestID , cloud function service error code -501005, error message Environment not found; at cloud.callFunction api;  home.js:119
    at new t (http://127.0.0.1:46528/appservice/__alphadev__/WACloud.js:1:72690)
    at u (http://127.0.0.1:46528/appservice/__alphadev__/WACloud.js:1:73404)
    at Object.t.returnAsFinalCloudSDKError (http://127.0.0.1:46528/appservice/__alphadev__/WACloud.js:1:73585)
    at success (http://127.0.0.1:46528/appservice/__alphadev__/WACloud.js:1:55461)
    at Function.function.a.(anonymous function) (http://127.0.0.1:46528/appservice/__dev__/WAService.js:7:6841)
    at Object.success (http://127.0.0.1:46528/appservice/__dev__/WAService.js:4:13377)
    at Q.<anonymous> (http://127.0.0.1:46528/appservice/__dev__/WAService.js:7:2427)
    at Q.emit (http://127.0.0.1:46528/appservice/__dev__/WAService.js:8:9515)
    at Function.<anonymous> (http://127.0.0.1:46528/appservice/__dev__/WAService.js:12:23919)
    at http://127.0.0.1:46528/appservice/__dev__/WAService.js:6:2179

Error: errCode: -404011 cloud function execution error | errMsg: cloud.callFunction:fail requestID , cloud function service error code -501005, error message Environment not found; at cloud.callFunction api;  index.js:145
    at new t (http://127.0.0.1:46528/appservice/__alphadev__/WACloud.js:1:72690)
    at u (http://127.0.0.1:46528/appservice/__alphadev__/WACloud.js:1:73404)
    at Object.t.returnAsFinalCloudSDKError (http://127.0.0.1:46528/appservice/__alphadev__/WACloud.js:1:73585)
    at success (http://127.0.0.1:46528/appservice/__alphadev__/WACloud.js:1:55461)
    at Function.function.a.(anonymous function) (http://127.0.0.1:46528/appservice/__dev__/WAService.js:7:6841)
    at Object.success (http://127.0.0.1:46528/appservice/__dev__/WAService.js:4:13377)
    at Q.<anonymous> (http://127.0.0.1:46528/appservice/__dev__/WAService.js:7:2427)
    at Q.emit (http://127.0.0.1:46528/appservice/__dev__/WAService.js:8:9515)
    at Function.<anonymous> (http://127.0.0.1:46528/appservice/__dev__/WAService.js:12:23919)
    at http://127.0.0.1:46528/appservice/__dev__/WAService.js:6:2179

**Comment by Bless-L** [comment]
应该是应该是云函数初始化问题，scr/app.js里的有个云函数初始化的代码，要换成你的云函数环境。还有你部署的每个云函数初始化时，环境也要换成你自己的环境

**Comment by lvjl** [comment]
好了，解决了，就是云函数没有初始化的问题，谢谢
